sonar.projectName=hackaton-video-management
sonar.projectKey=postech-group-fiap-188_hackaton-video-management
sonar.organization=postech-group-fiap-46
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Removi interfaces e infra das exclusões para o Sonar poder ler o código
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Deixe as exclusões de cobertura apenas para arquivos que realmente não possuem lógica testável
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts,**/infra/**,**/gateways/**,**/application/errors/**,**/adapters/**
sonar.coverage.minimum=80

sonar.typescript.tsconfigPath=tsconfig.json