sonar.projectName=hackaton-video-management
sonar.projectKey=postech-group-fiap-188_hackaton-video-management
sonar.organization=postech-group-fiap-46
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json

# Código de produção (apenas)
sonar.sources=src

# Onde ficam os testes: no teu repo eles estão em src (*.spec.ts) e também pode ter em /test
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Exclui os arquivos de teste da análise de código de produção
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts,**/*.spec.ts,**/*.e2e-spec.ts

# Coverage (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclui do coverage aquilo que não faz sentido testar + testes
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts,**/infra/**,**/gateways/**,**/application/errors/**,**/adapters/**,**/*.spec.ts,**/*.e2e-spec.ts
