sonar.projectKey=postech-group-fiap-188_hackaton-video-management
sonar.organization=postech-group-fiap-188

sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/migrations/**,**/prisma/**,**/main.ts,**/app.module.ts,**/infra/**,**/gateways/**,**/application/errors/**,**/adapters/**
sonar.coverage.minimum=80

sonar.typescript.tsconfigPath=tsconfig.json
