apiVersion: v1
kind: ConfigMap
metadata:
  name: hackaton-video-management-config
data:
  PORT: "3000"
  MONGO_DB: "videosdb"
  AWS_REGION: "us-east-1"
  # For localstack / non-prod environments you can set this:
  # AWS_ENDPOINT_URL: "http://localstack:4566"
  S3_INPUT_BUCKET_NAME: "videos-input"
  S3_OUTPUT_BUCKET_NAME: "videos-processed"
  SNS_PROCESSING_TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:video-processing-topic"
  SQS_STATUS_QUEUE_URL: "http://localstack:4566/000000000000/video-status-queue"
  MAX_VIDEO_BYTES: "2147483648"
  AUTH_DISABLED: "true"
