apiVersion: v1
kind: Secret
metadata:
  name: hackaton-video-management-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017"
  AWS_ACCESS_KEY_ID: "TROCAR AQUI"
  AWS_SECRET_ACCESS_KEY: "TROCAR AQUI"
