apiVersion: v1
kind: Secret
metadata:
  name: hackaton-video-management-secrets
type: Opaque
stringData:
  # Replace with your real values.
  MONGO_URI: "mongodb://mongo:27017"
  AWS_ACCESS_KEY_ID: "changeme"
  AWS_SECRET_ACCESS_KEY: "changeme"
