services:
  mongo:
    image: mongo:7
    container_name: hackaton-video-management_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  localstack:
    image: localstack/localstack:3
    container_name: hackaton-video-management_localstack
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackaton-video-management_api
    env_file:
      - .env.docker
    depends_on:
      - mongo
      - localstack
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_OPTIONS: "--enable-source-maps"
      START_CMD: "node --inspect=0.0.0.0:9229 dist/main.js"
    command: ["sh", "-lc", "/srv/docker/entrypoint.sh"]
