apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-video-management-config
data:
    PORT: {{ .Values.config.port | default "3000" | quote }}
    MONGO_DB_COLLECTION: {{ .Values.config.mongoDbCollection | quote }}
    S3_INPUT_BUCKET_NAME: {{ .Values.config.s3InputBucketName | quote }}
    S3_OUTPUT_BUCKET_NAME: {{ .Values.config.s3OutputBucketName | quote }}
    SNS_PROCESSING_TOPIC_ARN: {{ .Values.config.snsProcessingTopicArn | quote }}
    SQS_STATUS_QUEUE_URL: {{ .Values.config.sqsStatusQueueUrl | quote }}
    MAX_VIDEO_BYTES: {{ .Values.config.maxVideoBytes | quote }}

    NODE_ENV: {{ .Values.config.nodeEnv | default "production" | quote }}
    
    # AWS e Integrações
    AWS_REGION: {{ .Values.config.awsRegion | quote }}
