apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackaton-video-management
spec:
  ingressClassName: nginx
  rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: hackaton-video-management
                  port:
                    number: 80
