apiVersion: v1
kind: Secret
metadata:
  name: hackaton-video-management-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoDbUrl | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc }}
  AWS_SESSION_TOKEN: {{ .Values.secrets.awsSessionToken | b64enc }}
