name: Build

on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
      node_version:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (GitHub cache)
        if: ${{ env.ACT != 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: ${{ inputs.app_dir }}/package-lock.json

      - name: Setup Node (act - no cache)
        if: ${{ env.ACT == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        working-directory: ${{ inputs.app_dir }}
        run: npm ci

      - name: Build
        working-directory: ${{ inputs.app_dir }}
        run: npm run build
