name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      app_dir: app
      node_version: 22

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      app_dir: app
      node_version: 22

  tests:
    uses: ./.github/workflows/test.yml

  sonarqube:
    needs: tests
    uses: ./.github/workflows/sonarqube.yml
    with:
      app_dir: app
      node_version: 22
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
