name: SonarQube Quality Gate
on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
      node_version:
        required: true
        type: number
    secrets:
      SONAR_TOKEN:
        required: true


jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ${{ inputs.app_dir }} 
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}